# Generated by Django 3.1.1 on 2020-12-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
    ]
