# Generated by Django 3.1.1 on 2020-09-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200908_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Private_Post',
        ),
    ]
