# Generated by Django 3.1.1 on 2020-12-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
